version: '3.6'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: igd_test
      MYSQL_DATABASE: ms-account-service-db
    ports:
      - '3306:3306'
volumes:
  my-db:
